spring.application.name=internet-opinion-backend

spring.datasource.url=jdbc:postgresql://postgres:Rockyflair10$@db.rphwgrobzviqvspdowst.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Rockyflair10$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080